#!/bin/sh -e

# Create a "Release"

ver="$1"
VERSION="v$1"

# Parse command line parameter
if [ -z "$ver" ]
then
	echo "Argument version number missing"
	exit 1
fi

# Tag and push tags 
git tag -a "$VERSION" -m "Release $VERSION"
git push origin "v$ver"

# Also create a release branch
git checkout -b "$VERSION"
git push origin "$VERSION"
