#!/bin/sh


# Example of output format
#
# $ qstat
# Job id                    Name             User            Time Use S Queue
# ------------------------- ---------------- --------------- -------- - -----
# 1352661.abacus2            STDIN            pcingola        00:00:00 C sw             

user=`whoami`
echo "Job id                    Name             User            Time Use S Queue"
echo "------------------------- ---------------- --------------- -------- - -----"

for t in `cd $HOME/.bds/fakeClusterTasks/ ; find . -type f -iname "*.sh"`
do
	id=`basename $t .sh`
	echo "$id.clusterName       STDIN            $user        00:00:00 Q sw             "
done

