#!/bin/sh

# Show PID (this is expected by the executing program)
echo $$

# Create an executable script on "fakeCluster" queue
taskFile=$HOME/.bds/fakeClusterTasks/$$.sh

echo "#!/bin/sh" >> $taskFile
echo >> $taskFile
cat >> $taskFile

chmod a+x $taskFile

